### ISSUE TITLE
Potential Appointment Sorting Bug

### ISSUE THREAD

**Issue by Spiteless** [timfee/meet#14]
# Issue
When increasing DEFAULT_WORKDAY hours from 17 to 23, potential appointment slots in future days sort out of order in regard to Los Angeles timezone (hasn't been tested with other timezones at time of writing).

## Steps to reproduce
* Edit ending hours in config to greater than current set value of 17
* View appointments later than current date on localhost or online

```js
const DEFAULT_WORKDAY = [
  {
    start: {
      hour: 9,
    },
    end: {
      hour: 23, // <-- Changed 17 to 23
    },
  },
]
```

[Vercel Branch Deploy](https://online-calendar-git-testhoursupdate-spiteless.vercel.app/?duration=30&timeZone=America%2FLos_Angeles&selectedDate=2023-05-30)
* [Link to Github.com branch of deploy preview](https://github.com/spiteless/meet/tree/test_hours_update)

## Screenshots
<details>
<summary>View Screenshot</summary>
<img width="719" alt="image" src="https://github.com/timfee/meet/assets/5898009/9df67e85-7b3e-4108-bcee-59c4fa81c673">

</details>

**Comment by Spiteless** [comment]
Looks like this can be fixed by adding a sort:

```js
nst availabilitySorted = availability.sort((a, b) => {
    //sort by slot.start.getHours, then by slot.start.getMinutes
    if (a.start.getHours() < b.start.getHours()) {
      return -1;
    } else if (a.start.getHours() > b.start.getHours()) {
      return 1;
    }
    
    if (a.start.getMinutes() < b.start.getMinutes()) {
      return -1;
    } else if (a.start.getMinutes() < b.start.getMinutes()) {
      return 1;
    } else {
      return 0;
    }
  })
```

Currently I'm thinking of adding this to AvailabilityPicker.tsx, that looks like where the individual slots are generated

**Comment by Spiteless** [comment]
Upon further investigation the above statement isn't a solution. The date objects and be sorted already, comparing t1 > t2 will sort properly, but the issue being encountered has to do with UTC sorting of event times vs locale sorting of event times.

**Comment by timfee** [comment]
I think it had to do with `getISOString()` not being time-zoned correctly; let me know if this fix works!

**Comment by Spiteless** [comment]
Thanks for figuring this put! There's still a communication mismatch somewhere, I haven't had time to fully explore yet though
