### ISSUE TITLE
TODAY Availability ending at 5pm regardless of additional availability

### ISSUE THREAD

**Issue by Spiteless** [timfee/meet#15]
# Issue
Today availability ends at 5pm PST even if availability extends beyond 5pm. This is likely because PST is -7 UTC, so when the application is creating dates, the remaining slots are being shunted to the following day. 

# Details
This issue ties in with #14 , it's probably the same bug.

## Steps to reproduce
* Edit ending hours in config to greater than current set value of 17
* View appointments later than current date on localhost or online

```js
const DEFAULT_WORKDAY = [
  {
    start: {
      hour: 9,
    },
    end: {
      hour: 23, // <-- Changed 17 to 23
    },
  },
]
```

[Vercel Branch Deploy](https://online-calendar-git-testhoursupdate-spiteless.vercel.app/?duration=30&timeZone=America%2FLos_Angeles&selectedDate=2023-05-30)
* [Link to Github.com branch of deploy preview](https://github.com/spiteless/meet/tree/test_hours_update)

## Screenshots
<details>
<summary>View Screenshot</summary>
<img width="719" alt="image" src="https://github.com/timfee/meet/assets/5898009/93dd132c-71f4-45cc-a6eb-a6fbf65383b0">
<img width="719" alt="image" src="https://github.com/timfee/meet/assets/5898009/364f138d-3f9f-49d4-b367-248daf44d1ba">
<img width="719" alt="image" src="https://github.com/timfee/meet/assets/5898009/015a1330-1e6a-4c8a-8073-820a09d25734">

</details>

**Comment by timfee** [comment]
I think it had to do with getISOString() not being time-zoned correctly; let me know if this fix works!
