### ISSUE TITLE
Auto timezone improvement setter

### ISSUE THREAD

**Issue by ili-ad** [timfee/meet#23]
Love the project! I had a similar urge to make a simple white-labeled scheduler. Happy this is already out there!

One small improvement from a UX perspective is that the browser has timezone available via `Intl.DateTimeFormat().resolvedOptions().timeZone`.

Wrapping a setter in a UseEffect, e.g.:

```
import { useEffect } from 'react';
import { useProvider } from "@/context/AvailabilityContext"
import getTimezoneData from "@/lib/timezones"

const { groupLookupMap, timeZoneMap } = getTimezoneData()

export default function TimezonePicker() {
  const {
    state: { timeZone },
    dispatch,
  } = useProvider()

  useEffect(() => {
    // Set the timezone from the browser when the component mounts
    const browserTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    dispatch({
      type: "SET_TIMEZONE",
      payload: browserTimezone,
    });
  }, [dispatch]);

  // ... rest of TimezonePicker.ts
```

... automatically selects the user's browser's timezone without them having to go fish for it.

Thank you for this and kudos!

**Comment by timfee** [comment]
Hi there! I tried to handle this from the default state setter in availability context; is it not working for you?

```
// context/AvailabilityContext.tsx
const StateContext = createContext<StateType>({
  duration: ALLOWED_DURATIONS[0],
  start: Day.todayWithOffset(0),
  end: Day.todayWithOffset(14),
  timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  modal: "closed",
})

```

**Comment by ili-ad** [comment]
Thank you! Still finding my way around. I looked into putting it in the component because refreshing the page often just reloaded the previous selection. This is probably expected behavior given the URL params. Probably some fat fingering on my end...

**Comment by timfee** [comment]
Ah interesting. If the url parameter handling can be improved, I'm all ears :) 

So glad you found this useful and am grateful for your input!
